# -*- coding: utf-8 -*-
"""bigdata1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uaixgV9UXyCsWh_wa70uCZdKlnFHjoW
"""

first_name = input("Please Enter Your First Name: ")

print(first_name)

value = int(input("Please Enter a Number: ")) #input keyword always takes any value as a string. Thus, we use int() function
#it is called casting. It converts a value to different data types
if value < 0:
 print('The number is negative')
elif value == 0:
 print('The number is non-negative')
else:
 print('The number is positive')

total = 0
counter = 1
while counter <= 10: #stopping condition
 total = total + counter #sum
 counter += 1 #increament
print(total)

total = 0
for counter in range(1, 11, 1): #initialize, stopping condition, increament.
 total = total+ counter
print(total)

first_list = [1, 2, 3, 8]

print("First value of the list is ", first_list[0])
print("Last value of the list is ", first_list[-1])

for values in first_list:
 print(values)

#append
first_list.append(10)
print("After adding another element in the list, the list is ", first_list)
#modify
first_list[2] = 5
print("After modifying an element in the list, the list is ", first_list)
#insert: elements can be inserted in any positon/index
first_list.insert(2, 12)
print("After inserting an element in the list in the third position, the list is ", first_list)

zipCode = {'London':290, 'Leeds':578, 'Wolverhampton':911}
for key in zipCode:
 print(key, '= ', zipCode[key])

"""To explicitely find the list of keys or list value we can use the following"""
key_list = zipCode.keys()
value_list = zipCode.values()
print(key_list)
print(value_list)

zipCode['London'] = 666
for key in zipCode:
 print(key, '= ', zipCode[key])

zipCode['Birmingham'] = 111
for key in zipCode:
 print(key, '= ', zipCode[key])

def oddEven(num):
    if num % 2 == 0:
        print("The number is even")
    else:
        print("The number is odd")
    return

num = int(input("Please Enter a Number: "))
oddEven(num)

"""Display Fibonacci series up to 10 terms

"""

n = 10
a = 0
b = 1

print("Fibonacci Series:")

for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

"""Find the factorial of a given number. Ask the user to provide the number"""

num = int(input("Enter a number: "))
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

print("Factorial is:", factorial)

"""Write a program to print a right angle triangle using the for loop.


"""

rows = 5

for i in range(1, rows + 1):
    for j in range(i):
        print("*", end=" ")
    print()

"""Make a simple calculator that can add, subtract, multiply and divide two numbers using function.

"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Addition:", add(num1, num2))
print("Subtraction:", subtract(num1, num2))
print("Multiplication:", multiply(num1, num2))
print("Division:", divide(num1, num2))

"""Remove the first duplicate element of a list

"""

my_list = [1, 2, 3, 2, 4, 5]

seen = []
for item in my_list:
    if item not in seen:
        seen.append(item)

print(seen)

"""Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary.

"""

sample_dict = {"name": "Anderson", "age": 35, "salary": 5000, "city": "London"}
keys = ["name", "salary"]

new_dict = {}

for k in keys:
    new_dict[k] = sample_dict[k]

print(new_dict)

"""Write a Python program to convert two lists into a dictionary in a way that item from list_one is the key and item from list_two is the value."""

list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

result = {}

for i in range(len(list_one)):
    result[list_one[i]] = list_two[i]

print(result)